# 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/daxueshi
    username: root
    password: 969023014
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  devtools:
    restart:
      trigger-file: trigger.txt
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: 446110075@qq.com
    password: axptybjnnzcfbhcg
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    # 改成新邮箱
    from: 446110075@qq.com
  data:
    mongodb:
      database: discussion
      host: 127.0.0.1
  mvc:
    static-path-pattern: /static/**

# mybatis相关配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  config:
    key: ecnusoft
    ttl: 3600000
server:
  port: 8080