# 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/daxueshi
    username: root
    password: 969023014
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  devtools:
    restart:
      trigger-file: trigger.txt
  mail:
    username:
    password:
    host:
    properties: mail.smtp.ssl.enable = true
  data:
    mongodb:
      database: discussion
      host: 127.0.0.1

# mybatis相关配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  config:
    key: ecnusoft
    ttl: 3600000
